### ISSUE TITLE
Update "Parsing Command-Line Arguments" to use tools.cli 0.3.x and parse-opts

### ISSUE THREAD

**Issue by everett-toews** [clojure-cookbook/clojure-cookbook#427]
Update https://github.com/clojure-cookbook/clojure-cookbook/blob/master/03_general-computing/3-07_parse-command-line-arguments.asciidoc to use tools.cli 0.3.x and parse-opts.

**Comment by functor-soup** [comment]
@rkneufeld could you review #451  please?, this needs to be in the cookbook because cli usage pretty much legacy usage at this point.
