### ISSUE TITLE
source-highlight: could not find a language definition for clojure

### ISSUE THREAD

**Issue by Txellenne** [clojure-cookbook/clojure-cookbook#429]
Hi, There.
I got issues running the [bootstrap.sh script](https://github.com/clojure-cookbook/clojure-cookbook/blob/master/script/asciidoc/bootstrap.sh). It stops saying:

``` bash
** Adding /usr/share/source-highlight/clojure.lang **
```

 rather than `Setup Complete` as the script reads (line 119). 
Actually, there is not a `clojure.lang` file at  `/usr/share/source-highlight` dir as it's expected according the script (line 66 and sgts.) and when rendering the asciidoc I got as output a lot lines like the following:

``` bash
source-highlight: could not find a language definition for clojure
```

I'd appreciate any help on this.

**Comment by chbm** [comment]
The script is missing a definition of SUDO.
SUDO=sudo ./script/asciidoc/bootstrap.sh
or appropriate for your system

**Comment by rkneufeld** [comment]
@chbm I think this can probably just be `sudo` (changed).
