### ISSUE TITLE
Generating PDF using dblatex not working because of unknown language in source snippets

### ISSUE THREAD

**Issue by lenneman** [clojure-cookbook/clojure-cookbook#494]
When I want to create a PDF using dblatex it is not working.
The book.tex file is created, but afterwards latex cannot process it because of the following error:
```
book.tex:26255: Package Listings Error: language clojure undefined.
book.tex:26255: leading text: ...ing}[language={clojure},firstnumber=1,]
```

latex uses the package 'listings' and the code snippets are enclosed in the environment `\begin{lstlisting}[language={clojure} ...`
With that package several languages are supported [listings.pdf](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiflP6gnfbXAhXSzaQKHTrHAcEQFgg2MAE&url=http%3A%2F%2Ftexdoc.net%2Ftexmf-dist%2Fdoc%2Flatex%2Flistings%2Flistings.pdf&usg=AOvVaw2OY1AIk4CTM9PG5EMsrDCL) but unfortunately not "clojure", "text", "json" and "shell-session".

These languages are used in the asciidoc sources and are transformed literally into the book.xml and then into the book.tex.

replacing the languages with "Lisp" and "bash" will work and generate the PDF (but with wrong or insufficient code formatting).

So I cannot figure out what is wrong in my setup (e.g. missing stylsheet or latex package) or if it is just an unsupported process, which shouldn't be.

**Comment by rkneufeld** [comment]
I can't say I'm familiar with dblatex. Is a asciidoc not working anymore? O'Reilly's config is a little archaic and I'm hesitant to change how it works for existing asciidoc setups.

**Comment by lenneman** [comment]
Oh, asciidoc is working fine. I created a docbook xml file with asciidoc. This should then transformed into a PDF file where I'm using dblatex and the mentioned problem occurs.

**Comment by rkneufeld** [comment]
I would use asciidoc to output a PDF directly.

**Comment by jpliew** [comment]
@rkneufeld how about type out the command you use please?

**Comment by rkneufeld** [comment]
I haven’t built the book in a few years, but when I last did I used the scripts/commands here: https://github.com/clojure-cookbook/clojure-cookbook/blob/master/README.md#building-the-book

I don’t know the precise format identifier for pdf in asciidoc, but I presume the instructions can be modified for a different output type.

**Comment by lenneman** [comment]
ok, the instructions in the readme.md are for generating a HTML out of the asciidoc. This is also working fine.

And in general asciidoc is **not** generating directly to a PDF but to HTML, docbook and LaTex (which is experimental) only (see its manpage). So, a PDF can only be generated via docbook. Using dblatex converting from docbook to latex and then pdflatex to convert this latex to a PDF encounters the problem mentioned above.

**Comment by rkneufeld** [comment]
It may be then that we never had instructions for generating the PDF. Generally speaking we let O’Reiily generate the PDFs as they have a bunch of assets and styles that aren’t public.

**Comment by jpliew** [comment]
I found out the problem, the reason is `listings` used by `dblatex` to do the source code highlight does not have `clojure` language and this book uses custom styles from O'Reilly that is not included in this repo. I am working on a fix and will update soon.

**Comment by jpliew** [comment]
@lenneman you need to modify your asciidoc-dblatex.sty file to add the language.

[asciidoc-dblatex.sty.txt](https://github.com/clojure-cookbook/clojure-cookbook/files/1710661/asciidoc-dblatex.sty.txt)

Attached is the sample I made and I can build the PDF

Also need to edit all the source file to replace `shell-session` to `bash`

Hope this helps.
